packages:
  - 'apps/*'
  - 'packages/*'
  - 'client-sites/chroma-decks'
  - 'client-sites/eventcut-ai'
  - 'client-sites/humain-vc-decks'
  - 'client-sites/lossless-decks'
  - 'client-sites/reach-edu-hub'
  - 'client-sites/the-water-foundation'
