/**
 * /api/slide-decompose — write an empty per-slide stub file into the consuming
 * client-site's working tree. The Phase 1 → Phase 2 bridge from the
 * deck-iteration-workflow skill: the single-page variant keeps rendering as it
 * is; the new per-slide file is dormant until the founder recreates the slot
 * content into it during the next iteration session.
 *
 * Non-destructive: refuses to overwrite. Returns 409 if the file already
 * exists.
 *
 * Dev-only — `prerender = false`. The static Vercel build never carries this
 * route; the file write only happens against the developer's working tree.
 */
import fs from "node:fs/promises";
import path from "node:path";
import type { APIRoute } from "astro";
import { perSlideFilePath } from "../../registry-loader.js";

export const prerender = false;

function getOptionsOrThrow() {
  const opts = globalThis.__dididecksShellOptions;
  if (!opts) {
    throw new Error("@dididecks/shell: options not resolved");
  }
  return opts;
}

function stubContent(variantSlug: string, slot: string): string {
  return `---
// Generated by @dididecks/shell as a Phase 1 → Phase 2 decomposition stub.
// Recreate the slot content here; do not extract from the single-page variant.
---
<section data-slot="${slot}" data-variant="${variantSlug}"></section>
`;
}

export const POST: APIRoute = async ({ request }) => {
  const opts = getOptionsOrThrow();

  let body: { deckSlug?: string; variantSlug?: string; slot?: string; slug?: string };
  try {
    body = await request.json();
  } catch {
    return new Response(JSON.stringify({ error: "invalid JSON body" }), { status: 400 });
  }

  const { variantSlug, slot, slug } = body;
  if (!variantSlug || !slot || !slug) {
    return new Response(
      JSON.stringify({ error: "missing 'variantSlug', 'slot', or 'slug'" }),
      { status: 400 },
    );
  }

  const target = perSlideFilePath(opts.absolute.slidesComponentsRoot, variantSlug, slot, slug);

  // Non-destructive: refuse to overwrite.
  try {
    await fs.access(target);
    return new Response(
      JSON.stringify({ error: "file already exists", path: target }),
      { status: 409, headers: { "Content-Type": "application/json" } },
    );
  } catch {
    // ENOENT — proceed.
  }

  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, stubContent(variantSlug, slot), "utf-8");

  return new Response(JSON.stringify({ path: target, written: true }), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
};
